### ISSUE TITLE
Works for a few seconds with a UDR, then it just stops 

### ISSUE THREAD

**Issue by harrydimitriou** [mories76/udmprose-iptv#3]
Thanks for putting this together it does give me hope that KPN iptv will work with my UDR , however I went though the steps and I get some strange behaviour , every channel works for a few seconds but then  I get stb-nmc-400 error (binding met zender verbroken) . Any idea on why is that happening ?

**Comment by mories76** [comment]
Did you restart the TV tuner ?

**Comment by harrydimitriou** [comment]
I did yes , I get the progress bar , it reaches 100%  and loads the chanel  after a few secs it gives me that error .

**Comment by mories76** [comment]
I don't have an UDR myself but, I received input to this document by "nomnomnomhb". So I am pretty sure this should work.
Nog definitive checklist but : 
>  Have you created a "iptv" network ?
>  Is it on br2 ?
>  Did you change the port settings to the iptv lan on the  port where the tuner is attached ?
>  Could you check the output from the following command ? `podman container list -a`
Lookup for the uptime of the container in the status column. Is it restarting ?

Just some thoughts, hope it helps

**Comment by harrydimitriou** [comment]
I was rechecking the settings and I managed to find my mistake
In my case
export IPTV_LAN_INTERFACES="br2"

should actually be :
export IPTV_LAN_INTERFACES="br0"

Again thanks for putting this together, I owe you a beer if you are in the Hague area :P

**Comment by mories76** [comment]
Nice !
Thanks for reporting it back. Issue closed.
